year=int(input("輸入出生年份"))
years=year % 12
if years ==0 :
 print("monkey")
elif years==1:
    print("rooster")
elif years==2:
     print("dog")
elif years==3:
     print("pig")
elif years==4:
     print("rat")
elif years==5:
     print("ox")
elif years==6:
     print("tiger")
elif years==7:
     print("pig")
elif years==2:
     print("rabbit")
elif years==8:
     print("dragon")
elif years==9:
     print("snake")
elif years==10:
     print("horse")
elif years==11:
     print("sheep")
